Repository hmcts/am-role-assignment-service, pull requests merged in 2021-04, with the labels that each got.

#707 Ta 551 providerfor ia case api
  Jenkinsfile_CNP
  build.gradle
  pacts/am_role_assignment_service-Idam_api.json
  src/contractTest/java/uk/gov/hmcts/reform/roleassignment/CreateRoleAssignmentProviderTest.java
  src/contractTest/java/uk/gov/hmcts/reform/roleassignment/DeleteRoleAssignmentProviderTest.java
  src/contractTest/java/uk/gov/hmcts/reform/roleassignment/GetActorByIdRoleAssignmentProviderTest.java
  src/contractTest/java/uk/gov/hmcts/reform/roleassignment/GetRoleAssignmentProviderTest.java
  src/contractTest/java/uk/gov/hmcts/reform/roleassignment/IdamConsumerTest.java
  src/contractTest/java/uk/gov/hmcts/reform/roleassignment/SearchQueryRoleAssignmentProviderTest.java
  src/test/resources/attributes_orm_orgrole.json
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-707

#740 CVE Fix for commons-io
  build.gradle
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-740

#741 Fixing bugs related to mocking
  src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/DroolBase.java
  src/test/java/uk/gov/hmcts/reform/roleassignment/launchdarkly/FeatureConditionEvaluationTest.java
  src/test/java/uk/gov/hmcts/reform/roleassignment/oidc/JwtGrantedAuthoritiesConverterTest.java
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-741

#743 updated the max pool size settings for DB
  src/main/resources/application.yaml
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-743

#745 updated the keepAlive time in the connection pool settings
  src/main/resources/application.yaml
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-745

#747 AM-1321 adding contract test report to artifacts in Jenkins
  Jenkinsfile_CNP
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-747

#749 Dependabot and secret fix
  .dependabot/config.yml
  charts/am-role-assignment-service/Chart.yaml
  charts/am-role-assignment-service/values.yaml
  src/main/resources/application.yaml
  src/main/resources/bootstrap.yml
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-749

#750 enabling functional and mutation tests with security scan stage
  Jenkinsfile_nightly
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-750
