Repository hmcts/am-role-assignment-service, pull requests merged in 2021-08, with the labels that each got.

#871 AM-1475- test cases implementation for advance delete api by multiple…
  charts/am-role-assignment-service/Chart.yaml
  charts/am-role-assignment-service/values.aat.template.yaml
  charts/am-role-assignment-service/values.preview.template.yaml
  charts/am-role-assignment-service/values.yaml
  src/contractTest/java/uk/gov/hmcts/reform/roleassignment/DeleteRoleAssignmentProviderTest.java
  src/functionalTest/resources/features/F-010/F-010-Base-Root-Create.td.json
  src/functionalTest/resources/features/F-010/F-010-Base-Root.td.json
  src/functionalTest/resources/features/F-010/F-010.feature
  src/functionalTest/resources/features/F-010/F-010_Test_Data_Base-Create.td.json
  src/functionalTest/resources/features/F-010/F-010_Test_Data_Base.td.json
  src/functionalTest/resources/features/F-010/S-190.td.json
  src/functionalTest/resources/features/F-010/S-190_DeleteDataForRoleAssignmentsForOrgRoles.td.json
  src/functionalTest/resources/features/F-010/S-190_Multiple_Org_Role_Creation.td.json
  src/functionalTest/resources/features/F-010/S-191.td.json
  src/functionalTest/resources/features/F-010/S-191_DeleteDataForRoleAssignmentsForOrgRoles.td.json
  src/functionalTest/resources/features/F-010/S-191_Multiple_Org_Role_Creation.td.json
  src/functionalTest/resources/features/F-010/S-192.td.json
  src/functionalTest/resources/features/F-010/S-192_DeleteDataForRoleAssignmentsForOrgRoles.td.json
  src/functionalTest/resources/features/F-010/S-192_Multiple_Org_Role_Creation.td.json
  src/functionalTest/resources/features/F-010/S-193.td.json
  src/functionalTest/resources/features/F-010/S-193_DeleteDataForRoleAssignmentsForOrgRoles.td.json
  src/functionalTest/resources/features/F-010/S-193_Multiple_Org_Role_Creation.td.json
  src/functionalTest/resources/features/F-010/S-194.td.json
  src/integrationTest/java/uk/gov/hmcts/reform/roleassignment/controller/RoleAssignmentCreateAndDeleteIntegrationTest.java
  src/integrationTest/resources/sql/insert_multiple_assignments_to_delete.sql
  src/main/java/uk/gov/hmcts/reform/roleassignment/auditlog/AuditOperationType.java
  src/main/java/uk/gov/hmcts/reform/roleassignment/config/LaunchDarklyConfiguration.java
  src/main/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/DeleteAssignmentController.java
  src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/PersistenceService.java
  src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/deleteroles/DeleteRoleAssignmentOrchestrator.java
  src/main/java/uk/gov/hmcts/reform/roleassignment/launchdarkly/FeatureToggleService.java
  src/main/java/uk/gov/hmcts/reform/roleassignment/util/Constants.java
  src/main/java/uk/gov/hmcts/reform/roleassignment/versions/V1.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/DeleteAssignmentControllerTest.java
  src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/PersistenceServiceTest.java
  src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/deleteroles/DeleteRoleAssignmentOrchestratorTest.java
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-871

#919 Fixing the CVE-2021-28170
  build.gradle
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-919

#926 Fixing the CVE-2021-28170,CVE-2021-22119
  build.gradle
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-926

#932 1579 CVE nimbus lang tang
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-932

#940 Fixing the intermittent zap scan failures
  security.sh
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-940

#930 disabling static roles pact
  src/contractTest/java/uk/gov/hmcts/reform/roleassignment/GetRoleAssignmentProviderTest.java
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-930
