Repository hmcts/am-role-assignment-service, pull requests merged in 2021-05, with the labels that each got.

#764 AM: Updating the build.gradle to use Jitpack as a repo.
  build.gradle
  src/functionalTest/java/uk/gov/hmcts/reform/roleassignment/befta/RoleAssignmentTestAutomationAdapter.java
  src/functionalTest/java/uk/gov/hmcts/reform/roleassignment/befta/TestDataLoaderMain.java
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-764

#754 AM-1326: Am perftest fix
  src/main/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/CreateAssignmentController.java
  src/main/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/DeleteAssignmentController.java
  src/main/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/GetAssignmentController.java
  src/main/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/QueryAssignmentController.java
  src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/PersistenceService.java
  src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/createroles/CreateRoleAssignmentOrchestrator.java
  src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/createroles/CreateRoleAssignmentService.java
  src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/deleteroles/DeleteRoleAssignmentOrchestrator.java
  src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/getroles/RetrieveRoleAssignmentOrchestrator.java
  src/main/resources/application.yaml
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-754

#735 AM-1315: JRD - Additional tests for salaried judges in RAS
  src/functionalTest/resources/features/F-009/F-009-Base-Root.td.json
  src/functionalTest/resources/features/F-009/F-009.feature
  src/functionalTest/resources/features/F-009/F-009_Test_Data_Base.td.json
  src/functionalTest/resources/features/F-009/S-120.td.json
  src/functionalTest/resources/features/F-009/S-121.td.json
  src/functionalTest/resources/features/F-009/S-122.td.json
  src/functionalTest/resources/features/F-009/S-122_GetDataForRoleAssignments.td.json
  src/functionalTest/resources/features/common/RequestedRoleSalariedJudge.td.json
  src/functionalTest/resources/features/common/ResponseRequestedRoleSalariedJudge.td.json
  src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/DroolJudicialCategoryTest.java
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-735

#776 fixing the failing serenity reports
  build.gradle
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-776

#792 Enable DB self service read only access
  infrastructure/main.tf
  src/main/resources/application.yaml
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-792

#795 Add logs
  src/main/java/uk/gov/hmcts/reform/roleassignment/config/SecurityEndpointFilter.java
  src/main/resources/application.yaml
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-795

#805 Updating the audit.json file.
  audit.json
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-805

#806 Adding 90mins to the nightly trigger
  Jenkinsfile_nightly
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-806

#813 Spring upgrade
  build.gradle
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-813
