Repository hmcts/am-role-assignment-service, pull requests merged in 2021-09, with the labels that each got.

#968 junit for ccd roles
  src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/CCDCaseRolesTest.java
  src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/StaffCategoryCaseTest.java
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-968

#908 Ccd case roles configurations
  README.md
  build.gradle
  charts/am-role-assignment-service/Chart.yaml
  charts/am-role-assignment-service/values.yaml
  docker-compose.yml
  src/functionalTest/resources/features/F-001/S-005.td.json
  src/functionalTest/resources/features/F-001/S-006.td.json
  src/functionalTest/resources/features/F-007/S-071.td.json
  src/main/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/GetAssignmentController.java
  src/main/java/uk/gov/hmcts/reform/roleassignment/domain/model/RoleConfig.java
  src/main/java/uk/gov/hmcts/reform/roleassignment/domain/model/enums/FeatureFlagEnum.java
  src/main/java/uk/gov/hmcts/reform/roleassignment/domain/model/enums/RoleCategory.java
  src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/getroles/RetrieveRoleAssignmentOrchestrator.java
  src/main/java/uk/gov/hmcts/reform/roleassignment/feignclients/configuration/DataStoreApiFallback.java
  src/main/java/uk/gov/hmcts/reform/roleassignment/util/Constants.java
  src/main/java/uk/gov/hmcts/reform/roleassignment/util/JacksonUtils.java
  src/main/java/uk/gov/hmcts/reform/roleassignment/util/ValidationUtil.java
  src/main/resources/META-INF/kmodule.xml
  src/main/resources/db/migration/V1_3__ccd_flag_config_tables.sql
  src/main/resources/roleconfig/role_ccd.json
  src/main/resources/roleconfig/role_iac.json
  src/main/resources/validationrules/ccd/ccd-case-role-validation.drl
  src/main/resources/validationrules/core/load-case-data.drl
  src/test/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/GetAssignmentControllerTest.java
  src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/CCDCaseRolesTest.java
  src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/StaffCategoryCaseTest.java
  src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/getroles/RetrieveRoleAssignmentOrchestratorTest.java
  src/test/java/uk/gov/hmcts/reform/roleassignment/helper/TestDataBuilder.java
  src/test/java/uk/gov/hmcts/reform/roleassignment/util/JacksonUtilsTest.java
  src/test/java/uk/gov/hmcts/reform/roleassignment/util/ValidationUtilTest.java
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-908

#951 Add fortify implementation
  Jenkinsfile_nightly
  build.gradle
  config/fortify-client.properties
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-951

#960 AM-1600: Fix the BEFTA fw jar
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  build.gradle
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-960

#950 1605 Removing secrets
  src/main/resources/application.yaml
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-950
