Repository hmcts/am-role-assignment-service, pull requests merged in 2021-11, with the labels that each got.

#1021 Case allocator Junit
  src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/DroolBase.java
  src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/StaffCategoryCaseTest.java
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-1021

#1020 FTA for dummy jurisdiction
  src/functionalTest/resources/features/F-001/F-001.feature
  src/functionalTest/resources/features/F-001/S-123.td.json
  src/functionalTest/resources/features/F-001/S-123_CreateDataForRoleAssignment.td.json
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-1020

#1024 TF update for DB
  infrastructure/main.tf
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-1024

#1025 CVE-2021-22096 fix
  build.gradle
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-1025

#1026 Create postgres v11 DB on all environments
  infrastructure/main.tf
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-1026

#1034 Create the V11 DB password using terraform.
  infrastructure/main.tf
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-1034

#1035 Pointing to V11 DB post migration
  charts/am-role-assignment-service/Chart.yaml
  charts/am-role-assignment-service/values.aat.template.yaml
  charts/am-role-assignment-service/values.yaml
  infrastructure/main.tf
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-1035

#1040 Update suppressions.xml
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-1040

#1041 new CCD case roles
  src/main/resources/roleconfig/role_ccd.json
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-1041

#1033 Duplicate records logic
  src/functionalTest/resources/features/F-001/S-004.td.json
  src/functionalTest/resources/features/F-001/S-005.td.json
  src/functionalTest/resources/features/F-001/S-006.td.json
  src/functionalTest/resources/features/F-001/S-014.td.json
  src/functionalTest/resources/features/F-001/S-020.td.json
  src/functionalTest/resources/features/F-001/S-115.td.json
  src/functionalTest/resources/features/F-001/S-118.td.json
  src/functionalTest/resources/features/F-001/S-121.td.json
  src/functionalTest/resources/features/F-001/S-123.td.json
  src/functionalTest/resources/features/F-001/S-123_CreateDataForRoleAssignment.td.json
  src/functionalTest/resources/features/common/RequestedRole.td.json
  src/functionalTest/resources/features/common/ResponseRequestedRoleWithoutSubstantive.td.json
  src/main/java/uk/gov/hmcts/reform/roleassignment/domain/model/Assignment.java
  src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/createroles/CreateRoleAssignmentService.java
  src/main/java/uk/gov/hmcts/reform/roleassignment/util/JacksonUtils.java
  src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/createroles/CreateRoleAssignmentOrchestratorTest.java
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-1033

#1044 Remove v9.6 DB
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:am, prd:am, DO NOT MERGE, rel:am-role-assignment-service-pr-1044

#1042 added extra condition for fixing ccd duplicate case identification
  src/main/java/uk/gov/hmcts/reform/roleassignment/util/JacksonUtils.java
  src/test/java/uk/gov/hmcts/reform/roleassignment/helper/TestDataBuilder.java
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-1042

#1056 Upgrading to latest working versions of Flyway and Hibernate
  build.gradle
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-1056
