Repository hmcts/am-role-assignment-service, pull requests merged in 2022-10, with the labels that each got.

#1570 CVE issues and build failures
  build.gradle
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-1570

#1573 Jackson CVE-2022-42003
  build.gradle
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-1573

#1569 test case refactoring
  src/main/java/uk/gov/hmcts/reform/roleassignment/feignclients/configuration/DataStoreApiFallback.java
  src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/ChallengedAccessDroolsTest.java
  src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/ConflictOfInterestTest.java
  src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/DroolBase.java
  src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/IacJudicialCaseRoleTest.java
  src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/IacStaffCaseRoleTest.java
  src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/SpecificAccessDroolsTest.java
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-1569

#1560 CCD new case role configuration
  src/main/resources/roleconfig/role_ccd.json
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-1560

#1577 Combine prs branch
  build.gradle
  infrastructure/.terraform-version
  infrastructure/terraform.tf
Labels: ns:am, prd:am, no-changes, rel:am-role-assignment-service-pr-1577

#1582 Am specific rules
  src/functionalTest/resources/features/F-011/S-211_Org_Role_Creation.td.json
  src/main/resources/META-INF/kmodule.xml
  src/main/resources/roleconfig/role_common.json
  src/main/resources/validationrules/civil/civil-specific-access.drl
  src/main/resources/validationrules/core/specific-access-global.drl
  src/main/resources/validationrules/iac/common/iac-specific-access.drl
  src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/SpecificAccessDroolsTest.java
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-1582

#1593 build fix to remove jitpack
  build.gradle
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-1593

#1595 Fix build failure
  build.gradle
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-1595

#1597 ia_delete_creator_case_roles drool rule
  src/main/resources/validationrules/iac/common/iac-case-role-validation.drl
  src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/IacStaffCaseRoleTest.java
  src/test/java/uk/gov/hmcts/reform/roleassignment/helper/TestDataBuilder.java
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-1597
