Repository hmcts/am-role-assignment-service, pull requests merged in 2023-11, with the labels that each got.

#2040 AM-3033: IAC Jurisdiction changed from IAC to IA as Ref data it is he…
  src/main/resources/roleconfig/role_common.json
  src/main/resources/validationrules/core/organisational-role-mapping-common.drl
  src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/AllServicesOrgRoleTest.java
Labels: ns:am, prd:am, enable_keep_helm, rel:am-role-assignment-service-pr-2040

#2035 Am 2995 provision terraform postgres v15 perftest
  infrastructure/main.tf
  infrastructure/terraform.tf
  infrastructure/variables.tf
Labels: ns:am, prd:am, add-or-update, rel:am-role-assignment-service-pr-2035

#2042 AM-2993 v15 Migration - put perftest log level to DEBUG
  src/main/resources/application.yaml
Labels: ns:am, prd:am, add-or-update, rel:am-role-assignment-service-pr-2042

#2044 AM-2993 v15 Migration - put ITHC log level to DEBUG
  src/main/resources/application.yaml
Labels: ns:am, prd:am, add-or-update, rel:am-role-assignment-service-pr-2044

#2043 Revert "AM-2993 v15 Migration - put perftest log level to DEBUG"
  src/main/resources/application.yaml
Labels: ns:am, prd:am, add-or-update, rel:am-role-assignment-service-pr-2043

#2045 Revert "AM-2993 v15 Migration - put ITHC log level to DEBUG"
  src/main/resources/application.yaml
Labels: ns:am, prd:am, add-or-update, rel:am-role-assignment-service-pr-2045

#2049 AM-3047 Retire Bootstrap yaml
  charts/am-role-assignment-service/Chart.yaml
  charts/am-role-assignment-service/values.preview.template.yaml
  charts/am-role-assignment-service/values.yaml
  src/main/resources/application.yaml
  src/main/resources/bootstrap.yml
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-2049

#2056 Am 2975 v15 deprovision
  infrastructure/main.tf
Labels: ns:am, prd:am, no-changes, rel:am-role-assignment-service-pr-2056

#2036 AM-3020 Provision terraform v15 server RAS Prod AAT
  infrastructure/main.tf
  infrastructure/terraform.tf
  infrastructure/variables.tf
Labels: ns:am, prd:am, add-or-update, rel:am-role-assignment-service-pr-2036

#2060 Am 3020 Resync ITHC and Perftest
  Jenkinsfile_CNP
Labels: ns:am, prd:am, no-changes, rel:am-role-assignment-service-pr-2060

#2063 AM-2839 CVE-2023-35116 jackson upgraded to 2.15.3, Remove Suppression
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-2063

#2068 AM-3060 v15 Reader User Trigger
  infrastructure/main.tf
Labels: ns:am, prd:am, destroy, rel:am-role-assignment-service-pr-2068

#2071 AM-2840 CVE-2022-45688 Remove Suppression
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-2071

#2072 AM-3068 Pitest failures in Nightly - pitest-junit5-plugin upgraded to…
  build.gradle
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-2072

#1893 AM-2784: FTA - PublicLaw case roles
  src/functionalTest/resources/features/F-016/F-016-Base-Root.td.json
  src/functionalTest/resources/features/F-016/F-016.feature
  src/functionalTest/resources/features/F-016/F-016_Test_Data_Base.td.json
  src/functionalTest/resources/features/F-016/S-241.td.json
  src/functionalTest/resources/features/F-016/S-241_DeleteDataForRoleAssignmentsForOrgRoles.td.json
  src/functionalTest/resources/features/F-016/S-241_Delete_Case_Role.td.json
  src/functionalTest/resources/features/F-016/S-241_Org_Role_Creation.td.json
  src/functionalTest/resources/features/F-016/S-242.td.json
  src/functionalTest/resources/features/F-016/S-242_DeleteDataForRoleAssignmentsForOrgRoles.td.json
  src/functionalTest/resources/features/F-016/S-242_Delete_Case_Role.td.json
  src/functionalTest/resources/features/F-016/S-242_Org_Role_Creation.td.json
  src/functionalTest/resources/features/F-016/S-243.td.json
  src/functionalTest/resources/features/F-016/S-243_DeleteDataForRoleAssignmentsForOrgRoles.td.json
  src/functionalTest/resources/features/F-016/S-243_Delete_Case_Role.td.json
  src/functionalTest/resources/features/F-016/S-243_Org_Role_Creation.td.json
  src/functionalTest/resources/features/F-016/S-244.td.json
  src/functionalTest/resources/features/F-016/S-244_DeleteDataForRoleAssignmentsForOrgRoles.td.json
  src/functionalTest/resources/features/F-016/S-244_Delete_Case_Role.td.json
  src/functionalTest/resources/features/F-016/S-244_Org_Role_Creation.td.json
  src/functionalTest/resources/features/F-016/S-245.td.json
  src/functionalTest/resources/features/F-016/S-245_DeleteDataForRoleAssignmentsForOrgRoles.td.json
  src/functionalTest/resources/features/F-016/S-245_Delete_Case_Role.td.json
  src/functionalTest/resources/features/F-016/S-245_Org_Role_Creation.td.json
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-1893
