Repository hmcts/am-role-assignment-service, pull requests merged in 2023-03, with the labels that each got.

#1822 remove duplicate role
  build.gradle
  src/functionalTest/resources/features/F-015/S-223.td.json
  src/main/resources/roleconfig/role_common.json
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-1822

#1835 Fix Pact Publish & Update Local Pact DB Docker
  broker-compose.yml
  build.gradle
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-1835

#1860 AM-2728 CVE-2022-1471 snakeyaml suppression added, unrequired suppres…
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-1860

#1839 RAS:Change in mappings for fee paid judges for services
  src/functionalTest/resources/features/F-001/S-205_Org_Role_Creation.td.json
  src/functionalTest/resources/features/F-009/S-175.td.json
  src/main/resources/db/migration/V2_5__feepaid_judge_organisation_substantive.sql
  src/main/resources/roleconfig/role_common.json
  src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/AllServicesOrgRoleTest.java
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-1839

#1865 AM-2737 CVE-2023-20861 Suppression
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-1865

#1866 AM-2738 Nightly build slack messaging commented out as causing build …
  Jenkinsfile_nightly
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-1866
