Repository hmcts/am-role-assignment-service, pull requests merged in 2023-10, with the labels that each got.

#2003 AM-2953 CVE-2022-4244 AM-2952 CVE-2022-4245 Shared Suppression
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-2003

#2006 AM-2948 Temp disabling of Security Scan (Zap) in Nightly - Reenable
  Jenkinsfile_nightly
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-2006

#2009 AM-2958 Migrate to Workload Identity from aad-pod-identity - chart-ja…
  charts/am-role-assignment-service/Chart.yaml
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-2009

#2005 Am 2907 automate user count custom event reorg
  src/main/java/uk/gov/hmcts/reform/roleassignment/controller/UserCountController.java
  src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/UserCountService.java
  src/test/java/uk/gov/hmcts/reform/roleassignment/controller/UserCountControllerTest.java
  src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/UserCountServiceTest.java
Labels: ns:am, prd:am, enable_keep_helm, rel:am-role-assignment-service-pr-2005

#2019 AM-2987 CVE-2023-42794, AM-2988 CVE-2023-42795, AM-2989 CVE-2023-4564…
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-2019

#2021 AM-2987 Tomcat version var created and upgraded to 9.0.82
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-2021

#2016 AM-2954: Create a new system role for Civil
  charts/am-role-assignment-service/Chart.yaml
  charts/am-role-assignment-service/values.yaml
  src/main/resources/application.yaml
  src/main/resources/roleconfig/role_common.json
  src/main/resources/validationrules/core/organisational-role-mapping-common.drl
  src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/AllServicesOrgRoleTest.java
Labels: ns:am, prd:am, enable_keep_helm, rel:am-role-assignment-service-pr-2016

#2027 AM-3002 CVE-2023-5072 Suppression
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-2027

#2013 COT-572 update FPL staff case roles to accept any classification
  src/main/resources/roleconfig/role_common.json
  src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/CaseRolesDroolsTest.java
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-2013

#2034 AM-3005: Add a new drool rule to support system user for IAC
  charts/am-role-assignment-service/Chart.yaml
  src/main/resources/roleconfig/role_common.json
  src/main/resources/validationrules/core/organisational-role-mapping-common.drl
  src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/AllServicesOrgRoleTest.java
Labels: ns:am, prd:am, enable_keep_helm, rel:am-role-assignment-service-pr-2034

#2033 Am 2975 provision terraform postgres v15 ithc
  infrastructure/main.tf
  infrastructure/terraform.tf
  infrastructure/variables.tf
Labels: ns:am, prd:am, add-or-update, rel:am-role-assignment-service-pr-2033
