Repository hmcts/am-role-assignment-service, pull requests merged in 2023-04, with the labels that each got.

#1869 AM-2740 CVE-2023-20860 Suppression
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-1869

#1872 AM-2747 temp disable SecurityScan in Nightly build
  Jenkinsfile_nightly
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-1872

#1880 AM-2776 CVE-2023-20863 Suppression
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-1880

#1878 AM-2745
  src/main/resources/roleconfig/role_ccd.json
  src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/CCDCaseRolesTest.java
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-1878
