Repository hmcts/am-role-assignment-service, pull requests merged in 2024-11, with the labels that each got.

#2370 Revert "DTSAM-578 CVE-2024-9329 glassfish Suppression"
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-2370

#2373 DTSAM-603 Temporary disable FTAs that use CCD Validation and fix issues
  Jenkinsfile_CNP
  Jenkinsfile_nightly
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-2373

#2354 Dtsam 573 update paginated RoleAssignment retrieval query
  src/contractTest/java/uk/gov/hmcts/reform/roleassignment/CreateRoleAssignmentProviderTest.java
  src/contractTest/java/uk/gov/hmcts/reform/roleassignment/DeleteRoleAssignmentProviderTest.java
  src/contractTest/java/uk/gov/hmcts/reform/roleassignment/GetActorByIdRoleAssignmentProviderTest.java
  src/contractTest/java/uk/gov/hmcts/reform/roleassignment/GetRoleAssignmentProviderTest.java
  src/contractTest/java/uk/gov/hmcts/reform/roleassignment/SearchQueryRoleAssignmentProviderTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/roleassignment/controller/QueryAssignmentIntegrationTest.java
  src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/PersistenceService.java
  src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/ValidationModelService.java
  src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/deleteroles/DeleteRoleAssignmentOrchestrator.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/PersistenceServiceTest.java
  src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/ValidationModelServiceTest.java
  src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/deleteroles/DeleteRoleAssignmentOrchestratorTest.java
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-2354

#2374 DTSAM-603 PRL FTA update case id
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  src/functionalTest/resources/features/F-014/S-219.td.json
  src/functionalTest/resources/features/F-014/S-220.td.json
  src/functionalTest/resources/features/F-015/S-223.td.json
  src/functionalTest/resources/features/F-015/S-224.td.json
  src/functionalTest/resources/features/F-015/S-225.td.json
  src/functionalTest/resources/features/F-015/S-226.td.json
  src/functionalTest/resources/features/F-015/S-227.td.json
  src/functionalTest/resources/features/F-015/S-228.td.json
  src/functionalTest/resources/features/F-015/S-229.td.json
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-2374

#2379 CME-121 Database monitoring and alerting on AM repositories - Unsync …
  Jenkinsfile_CNP
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-2379

#2378 CME-121: Database monitoring and alerting on AM repositories
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:am, prd:am, aat/add-or-update, prod/add-or-update, ithc/add-or-update, rel:am-role-assignment-service-pr-2378

#2380 CME-121: remove action group config to test deletions
  infrastructure/main.tf
Labels: ns:am, prd:am, aat/no-changes, ithc/destroy, rel:am-role-assignment-service-pr-2380

#2381 CME-121: Provide minimum required config
  infrastructure/main.tf
Labels: ns:am, prd:am, aat/add-or-update, ithc/add-or-update, rel:am-role-assignment-service-pr-2381

#2385 DTSAM-611 Fix RAS FTA issue with XUI S2S token
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  src/functionalTest/java/uk/gov/hmcts/reform/roleassignment/befta/RoleAssignmentTestAutomationAdapter.java
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-2385

#2364 DTSAM-571 Audit byPassOrgDroolRule when receiving ORG roles from ORM
  src/functionalTest/resources/features/F-001/F-001_Test_Data_Base.td.json
  src/functionalTest/resources/features/F-002/F-002_Test_Data_Base.td.json
  src/functionalTest/resources/features/F-003/F-003_Test_Data_Base.td.json
  src/functionalTest/resources/features/F-005/F-005_Test_Data_Base.td.json
  src/functionalTest/resources/features/F-006/F-006_Test_Data_Base.td.json
  src/functionalTest/resources/features/F-007/F-007_Test_Data_Base.td.json
  src/functionalTest/resources/features/F-008/F-008_Test_Data_Base.td.json
  src/functionalTest/resources/features/F-009/F-009_Test_Data_Base.td.json
  src/functionalTest/resources/features/F-010/F-010_Test_Data_Base-Create.td.json
  src/functionalTest/resources/features/F-010/F-010_Test_Data_Base.td.json
  src/functionalTest/resources/features/F-011/F-011_Test_Data_Base.td.json
  src/functionalTest/resources/features/F-012/F-012_Test_Data_Base.td.json
  src/functionalTest/resources/features/F-013/F-013_Test_Data_Base.td.json
  src/functionalTest/resources/features/F-014/F-014_Test_Data_Base.td.json
  src/functionalTest/resources/features/F-015/F-015_Test_Data_Base.td.json
  src/functionalTest/resources/features/F-016/F-016_Test_Data_Base.td.json
  src/functionalTest/resources/features/F-017/F-017_Test_Data_Base.td.json
  src/functionalTest/resources/features/F-017/F-017_Test_Data_Base_Get.td.json
  src/functionalTest/resources/features/F-018/F-018_Test_Data_Base.td.json
  src/functionalTest/resources/features/common/CreationDataBaseForRoleAssignment.td.json
  src/functionalTest/resources/features/common/CreationDataForRoleAssignment.td.json
  src/functionalTest/resources/features/common/DeleteDataForRoleAssignments.td.json
  src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/ValidationModelService.java
  src/main/resources/validationrules/core/organisational-role-mapping-common.drl
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-2364

#2365 DTSAM-572 Audit use of case-allocator rules for CCD case-roles
  src/main/resources/validationrules/core/case-allocator-global.drl
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-2365

#2386 CME-121 : set thresholds to 10 percent
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:am, prd:am, aat/add-or-update, prod/add-or-update, ithc/destroy, rel:am-role-assignment-service-pr-2386
