Repository hmcts/am-role-assignment-service, pull requests merged in 2024-05, with the labels that each got.

#2222 DTSAM-288 Temp disable of FTAs with CCD Validation
  Jenkinsfile_CNP
  Jenkinsfile_nightly
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-2222

#2204 AM-3035 Schema Owner Trigger Prod 5
  infrastructure/main.tf
Labels: ns:am, prd:am, aat/destroy, rel:am-role-assignment-service-pr-2204, prod/no-changes

#2212 AM-3060 Reader User Trigger 5 Prod
  infrastructure/main.tf
Labels: ns:am, prd:am, aat/destroy, rel:am-role-assignment-service-pr-2212, prod/destroy

#2100 AM-3039 Connect to v15 Prod - password user and host taken from keyva…
  charts/am-role-assignment-service/Chart.yaml
  charts/am-role-assignment-service/values.yaml
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-2100

#2224 DTSAM-303 Unsync Perftest from Master
  Jenkinsfile_CNP
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-2224

#2231 DTSAM-303 Resize PG - pgsql_sku GP_Standard_D4s_v3 added for AAT
  infrastructure/aat.tfvars
Labels: ns:am, prd:am, aat/add-or-update, prod/no-changes, rel:am-role-assignment-service-pr-2231

#2234 AM-3045 Decommission V11 DB - Unsync ITHC branch from Master and resy…
  Jenkinsfile_CNP
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-2234

#2235 AM-3045 Decommission V11 DB ITHC - Update TF Key Vault Mappings Point…
  infrastructure/main.tf
Labels: ns:am, prd:am, aat/add-or-update, ithc/add-or-update, rel:am-role-assignment-service-pr-2235

#2238 AM-3045 Decommission V11 DB Master - Update TF Key Vault Mappings Poi…
  infrastructure/main.tf
Labels: ns:am, prd:am, aat/add-or-update, prod/add-or-update, rel:am-role-assignment-service-pr-2238

#2239 AM-3045 Decommission V11 DB Master - V11 TF module removed, azurerm p…
  infrastructure/main.tf
  infrastructure/terraform.tf
Labels: ns:am, prd:am, aat/destroy, prod/destroy, rel:am-role-assignment-service-pr-2239

#2241 AM-3045 Decommission V11 DB - Resync ITHC with Master branch
  Jenkinsfile_CNP
Labels: ns:am, prd:am

#2237 DTSAM-323 Update AAT Chart Files After V11 Decommission - Hardcoded v…
  charts/am-role-assignment-service/values.aat.template.yaml
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-2237

#2244 DTSAM-322 Decommission custom Postgres-V15 key vault values now that …
  charts/am-role-assignment-service/Chart.yaml
  charts/am-role-assignment-service/values.yaml
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-2244
