Repository hmcts/am-role-assignment-service, pull requests merged in 2024-04, with the labels that each got.

#2191 DTSAM-185 CVE-2024-1597 postgresql upgraded to 42.6.1, suppression removed
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-2191

#2187 DTSAM-236 :Challenged Access for Fee-Paid Judicial members
  charts/am-role-assignment-service/values.aat.template.yaml
  src/main/java/uk/gov/hmcts/reform/roleassignment/domain/model/enums/FeatureFlagEnum.java
  src/main/resources/db/migration/V20240328_236__DTSAM-236_sscs_challenged_flag_config_tables.sql
  src/main/resources/validationrules/core/challenged-access-global.drl
  src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/ChallengedAccessDroolsTest.java
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-2187

#2200 AM-3143 Disable enable_temp_tablespaces_on_local_ssd in v15 Prod
  infrastructure/main.tf
Labels: ns:am, prd:am, aat/add-or-update, rel:am-role-assignment-service-pr-2200

#2202 DTSPO-17373 Jenkins Build Failed at Security Scan stage, Zap image up…
  Jenkinsfile_nightly
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-2202

#2198 AM-3035 Schema Owner Trigger Prod
  infrastructure/main.tf
Labels: ns:am, prd:am, aat/destroy, rel:am-role-assignment-service-pr-2198

#2199 AM-3060 Reader User Trigger 4 Prod
  infrastructure/main.tf
Labels: ns:am, prd:am, aat/destroy, rel:am-role-assignment-service-pr-2199

#2207 Revert "DTSPO-17373 Jenkins Build Failed at Security Scan stage, Zap image up…"
  Jenkinsfile_nightly
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-2207

#2201 DTSAM-254 update ET hearing-judge case role
  src/main/resources/validationrules/employment/employment-case-role-validation-judicial.drl
  src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/CaseRolesDroolsTest.java
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-2201

#2211 AM-3076 Enable 'sscs_challenged_1_0' in Prod
  src/main/resources/db/migration/V20240416_3076__AM-3076_Enable_sscs_challenged_1_0_Prod.sql
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-2211

#2210 AM-3076 Enable 'sscs_wa_1_0' in Prod
  src/main/resources/db/migration/V20240417_3076__AM-3076_Enable_sscs_wa_1_0_Prod.sql
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-2210

#2208 FTA - ET Case roles
  src/functionalTest/resources/features/F-018/F-018-Base-Root.td.json
  src/functionalTest/resources/features/F-018/F-018.feature
  src/functionalTest/resources/features/F-018/F-018_Test_Data_Base.td.json
  src/functionalTest/resources/features/F-018/S-261.td.json
  src/functionalTest/resources/features/F-018/S-261_DeleteDataForRoleAssignmentsForOrgRoles.td.json
  src/functionalTest/resources/features/F-018/S-261_Delete_Case_Role.td.json
  src/functionalTest/resources/features/F-018/S-261_Org_Role_Creation.td.json
  src/functionalTest/resources/features/F-018/S-262.td.json
  src/functionalTest/resources/features/F-018/S-262_DeleteDataForRoleAssignmentsForOrgRoles.td.json
  src/functionalTest/resources/features/F-018/S-262_Delete_Case_Role.td.json
  src/functionalTest/resources/features/F-018/S-262_Org_Role_Creation.td.json
  src/functionalTest/resources/features/F-018/S-263.td.json
  src/functionalTest/resources/features/F-018/S-263_DeleteDataForRoleAssignmentsForOrgRoles.td.json
  src/functionalTest/resources/features/F-018/S-263_Delete_Case_Role.td.json
  src/functionalTest/resources/features/F-018/S-263_Org_Role_Creation.td.json
  src/functionalTest/resources/features/F-018/S-264.td.json
  src/functionalTest/resources/features/F-018/S-264_DeleteDataForRoleAssignmentsForOrgRoles.td.json
  src/functionalTest/resources/features/F-018/S-264_Delete_Case_Role.td.json
  src/functionalTest/resources/features/F-018/S-264_Org_Role_Creation.td.json
  src/functionalTest/resources/features/F-018/S-265.td.json
  src/functionalTest/resources/features/F-018/S-265_DeleteDataForRoleAssignmentsForOrgRoles.td.json
  src/functionalTest/resources/features/F-018/S-265_Delete_Case_Role.td.json
  src/functionalTest/resources/features/F-018/S-265_Org_Role_Creation.td.json
  src/functionalTest/resources/features/F-018/S-266.td.json
  src/functionalTest/resources/features/F-018/S-266_DeleteDataForRoleAssignmentsForOrgRoles.td.json
  src/functionalTest/resources/features/F-018/S-266_Delete_Case_Role.td.json
  src/functionalTest/resources/features/F-018/S-266_Org_Role_Creation.td.json
  src/functionalTest/resources/features/F-018/S-267.td.json
  src/functionalTest/resources/features/F-018/S-267_DeleteDataForRoleAssignmentsForOrgRoles.td.json
  src/functionalTest/resources/features/F-018/S-267_Delete_Case_Role.td.json
  src/functionalTest/resources/features/F-018/S-267_Org_Role_Creation.td.json
  src/functionalTest/resources/features/F-018/S-268.td.json
  src/functionalTest/resources/features/F-018/S-268_DeleteDataForRoleAssignmentsForChallengedAccess.td.json
  src/functionalTest/resources/features/F-018/S-268_DeleteDataForRoleAssignmentsForOrgRoles.td.json
  src/functionalTest/resources/features/F-018/S-268_Org_Role_Creation.td.json
Labels: ns:am, prd:am, enable_keep_helm, rel:am-role-assignment-service-pr-2208

#2217 DTSAM-252 Helm chart upgrade - chart-java 5.2.0 ,autoscaling disabled
  charts/am-role-assignment-service/Chart.yaml
  charts/am-role-assignment-service/values.yaml
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-2217
