Repository hmcts/am-role-assignment-service, pull requests merged in 2024-03, with the labels that each got.

#2163 AM-3138: FTA fix.
  src/functionalTest/resources/features/F-011/S-231.td.json
  src/functionalTest/resources/features/F-011/S-231_Access_Requested.td.json
  src/functionalTest/resources/features/F-011/S-232.td.json
  src/functionalTest/resources/features/F-011/S-232_Access_Requested.td.json
  src/functionalTest/resources/features/F-017/F-017-Base-Root.td.json
  src/functionalTest/resources/features/F-017/S-256_DeleteDataForRoleAssignmentsForOrgRoles.td.json
  src/functionalTest/resources/features/F-017/S-256_Org_Role_Creation.td.json
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-2163

#2164 AM-3024 Migrate Data RAS AAT - Schema Owner Fix
  infrastructure/aat.tfvars
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:am, prd:am, add-or-update, rel:am-role-assignment-service-pr-2164

#2167 AM-3138: FTA fix
  src/functionalTest/resources/features/F-009/F-009.feature
  src/functionalTest/resources/features/F-009/S-175.td.json
  src/functionalTest/resources/features/F-017/F-017.feature
  src/functionalTest/resources/features/F-017/S-256.td.json
  src/functionalTest/resources/features/F-017/S-256_Org_Role_Creation.td.json
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-2167

#2168 DTSAM-163 Reverting Preview CCD Data Store url
  charts/am-role-assignment-service/values.preview.template.yaml
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-2168

#2169 AM-3024 Migrate Data RAS AAT - Schema Owner Bump 2
  infrastructure/main.tf
Labels: ns:am, prd:am, destroy, rel:am-role-assignment-service-pr-2169

#2110 AM-3060 v15 Reader User Trigger 2 AAT, ITHC, Perftest, Demo
  infrastructure/main.tf
Labels: ns:am, prd:am, destroy, rel:am-role-assignment-service-pr-2110

#2170 DTSAM-163 EV flag option to allow FTAs that use CCD Validation to be switched off
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  src/functionalTest/java/uk/gov/hmcts/reform/roleassignment/befta/RasDefaultMultiSourceFeatureToggleService.java
  src/functionalTest/java/uk/gov/hmcts/reform/roleassignment/befta/RasEnvironmentVariableToggleService.java
  src/functionalTest/resources/features/F-000/F-000.feature
  src/functionalTest/resources/features/F-000/S-000.04.td.json
  src/functionalTest/resources/features/F-000/S-000.05.td.json
  src/functionalTest/resources/features/F-001/F-001.feature
  src/functionalTest/resources/features/F-008/F-008.feature
  src/functionalTest/resources/features/F-011/F-011.feature
  src/functionalTest/resources/features/F-012/F-012.feature
  src/functionalTest/resources/features/F-013/F-013.feature
  src/functionalTest/resources/features/F-014/F-014.feature
  src/functionalTest/resources/features/F-015/F-015.feature
  src/functionalTest/resources/features/F-016/F-016.feature
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-2170

#2173 AM-3024 Migrate Data RAS AAT - Schema Owner Bump 3
  infrastructure/main.tf
Labels: ns:am, prd:am, destroy, rel:am-role-assignment-service-pr-2173

#2178 AM-3060 v15 Reader User Trigger 3 AAT, ITHC, Perftest, Demo
  infrastructure/main.tf
Labels: ns:am, prd:am, destroy, rel:am-role-assignment-service-pr-2178

#2111 AM-3117 Update AAT Chart for Staging RAS
  charts/am-role-assignment-service/values.aat.template.yaml
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-2111

#2186 DTSAM-185 : CVE Suppression CVE-2024-1597
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-2186
