Repository hmcts/am-role-assignment-service, pull requests merged in 2024-02, with the labels that each got.

#2132 DTSAM-98 : Case-Allocator Role Assignments for PRL System Users
  charts/am-role-assignment-service/Chart.yaml
  charts/am-role-assignment-service/values.yaml
  src/main/resources/application.yaml
  src/main/resources/roleconfig/role_common.json
  src/main/resources/validationrules/core/organisational-role-mapping-common.drl
  src/main/resources/validationrules/privatelaw/privatelaw-system-user-validation.drl
  src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/AllServicesOrgRoleTest.java
  src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/PrivateLawSystemRoleTest.java
Labels: ns:am, prd:am, enable_keep_helm, rel:am-role-assignment-service-pr-2132

#2062 GA-7 Add new drool rule for professional org roles
  src/main/java/uk/gov/hmcts/reform/roleassignment/domain/model/enums/FeatureFlagEnum.java
  src/main/resources/db/migration/V20231122_7__GA-7_GA_PRM_1_0_base_flag_addition.sql
  src/main/resources/roleconfig/role_prm.json
  src/main/resources/validationrules/prm/prm-role-mapping-validation.drl
  src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/PrmOrgRoleTest.java
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-2062

#2140 DTSAM-134 Allow Flyway DB Migrations Out of Order
  src/main/resources/application.yaml
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-2140

#2141 DTSAM-134 Allow Flyway DB Migrations Out of Order - build.gradle conf…
  build.gradle
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-2141

#2121 Functional Tests for GA-7
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  src/functionalTest/java/uk/gov/hmcts/reform/roleassignment/befta/RoleAssignmentTestAutomationAdapter.java
  src/functionalTest/resources/features/F-017/F-017-Base-Root.td.json
  src/functionalTest/resources/features/F-017/F-017.feature
  src/functionalTest/resources/features/F-017/F-017_Test_Data_Base.td.json
  src/functionalTest/resources/features/F-017/F-017_Test_Data_Base_Get.td.json
  src/functionalTest/resources/features/F-017/S-250.td.json
  src/functionalTest/resources/features/F-017/S-250_DeleteDataForRoleAssignmentsForOrgRoles.td.json
  src/functionalTest/resources/features/F-017/S-251.td.json
  src/functionalTest/resources/features/F-017/S-252.td.json
  src/functionalTest/resources/features/F-017/S-253.td.json
  src/functionalTest/resources/features/F-017/S-254.td.json
  src/functionalTest/resources/features/F-017/S-255.td.json
  src/functionalTest/resources/features/F-017/S-256.td.json
  src/functionalTest/resources/features/F-017/S-256_DeleteDataForRoleAssignmentsForOrgRoles.td.json
  src/functionalTest/resources/features/F-017/S-256_Org_Role_Creation.td.json
  src/functionalTest/resources/features/F-017/S-257.td.json
Labels: ns:am, prd:am, no-changes, rel:am-role-assignment-service-pr-2121

#2145 DTSAM-137 CVE-2023-34042 Suppression
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-2145

#2147 DTSAM-137 CVE-2023-34042 spring-security upgraded to 5.7.11
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-2147

#2091 AM-3004 : Add hearing-viewer & hearing-manager to CTSC users for SSCS
  src/main/resources/roleconfig/role_common.json
  src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/AllServicesOrgRoleTest.java
Labels: ns:am, prd:am, no-changes, enable_keep_helm, rel:am-role-assignment-service-pr-2091

#2152 DTSAM-154 DTSAM-155 CVE-2024-25710 CVE-2024-26308 Suppression
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-2152

#2153 DTSAM-154 DTSAM-155 CVE-2024-25710 CVE-2024-26308 Fix
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-2153

#2159 AM-3134 Create new role for SSCS 'post-hearing-judge' - new entry add…
  src/main/resources/roleconfig/role_sscs.json
  src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/AllServicesOrgRoleTest.java
Labels: ns:am, prd:am, enable_keep_helm, rel:am-role-assignment-service-pr-2159
