Repository hmcts/am-role-assignment-service, pull requests merged in 2025-05, with the labels that each got.

#2482 CME-437: batch tables backup and delete
  src/main/resources/db/migration/V20250328_437__CME-437_batch_tables.sql
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-2482

#2503 DTSAM-875 Temp disable of FTAs with CCD Validation
  Jenkinsfile_CNP
  Jenkinsfile_nightly
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-2503

#2506 DTSAM-865
  build.gradle
Labels: ns:am, prd:am, rel:am-role-assignment-service-pr-2506
